"""add users table

Revision ID: 4160900c2e0a
Revises: 4d09e704ee43
Create Date: 2025-12-26 13:21:52.167371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4160900c2e0a'
down_revision: Union[str, Sequence[str], None] = '4d09e704ee43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address of the user, used for login and notifications'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Hashed password of the user, used for authentication'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment="Indicates whether the user's email has been verified"),
    sa.Column('user_type', sa.Enum('USER', 'ADMIN', name='enum_user_type'), server_default='USER', nullable=False, comment='Type of user, indicating their role in the system'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='User last logged in'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique record identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation time (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update time (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    op.create_index(op.f('ix__users__email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__users__email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
